# =============================================================================
# Staging Environment Stack
# =============================================================================
# 스테이징 환경: PostgreSQL 17 + Redis 7.4
#
# 사용법:
#   docker stack deploy -c stacks/stg.yml stg
#
# 접근:
#   - Web: stg.nextcandle.io (외부)
#   - PostgreSQL: localhost:5433 (nextcandle_stg / stg_user)
#   - Redis: localhost:6380 (redis_stg_user)
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # PostgreSQL 17 + pgvector - 스테이징 환경
  # ---------------------------------------------------------------------------
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - ../.data/stg/postgres:/var/lib/postgresql/data
    configs:
      - source: postgres_config
        target: /etc/postgresql/postgresql.conf
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    networks:
      - internal
      - traefik-public
    ports:
      - target: 5432
        published: 5433
        mode: host
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d $$(cat /run/secrets/postgres_db)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ---------------------------------------------------------------------------
  # Redis 7.4 - 스테이징 환경
  # ---------------------------------------------------------------------------
  redis:
    image: redis:7.4
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        redis-server \
          --requirepass "$$(cat /run/secrets/redis_password)" \
          --maxmemory 128mb \
          --maxmemory-policy noeviction \
          --appendonly yes
    volumes:
      - ../.data/stg/redis:/data
    networks:
      - internal
      - traefik-public
    secrets:
      - redis_password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:
    driver: overlay
  traefik-public:
    external: true

configs:
  postgres_config:
    file: ../configs/postgres/postgresql.conf

secrets:
  postgres_db:
    external: true
    name: stg_postgres_db
  postgres_user:
    external: true
    name: stg_postgres_user
  postgres_password:
    external: true
    name: stg_postgres_password
  redis_password:
    external: true
    name: stg_redis_password
